### PR TITLE
Finish this module

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by stevemao** [comment]
@hemanth I'm planing to use this module for conventional-changelog (https://github.com/ajoslin/conventional-changelog) which is used by Angular, Karma and some Yeoman generators. I can't use this now because it's incomplete. Is there anything I can do to get this one merged quicker? Thanks.

**Comment by hemanth** [comment]
@stevemao Awesome! Thanks, merging it right away.

**Comment by hemanth** [comment]
Released `v1.0.0` thanks.

**Comment by hemanth** [comment]
BTW, let me know you npm username, will add you as a owner :+1:

**Comment by stevemao** [comment]
Thanks @hemanth , my npm username is `stevemao`

**Comment by stevemao** [comment]
If you don't mind, you can add me to this repo and i'll add more tests :smile:

**Comment by hemanth** [comment]
Done :+1:

**Comment by stevemao** [comment]
Thank you so much @hemanth :smile:

**Comment by hemanth** [comment]
Thank you!

**Pull request merged**
