### PR TITLE
Add remove bom character if present at the top of the file

### PR DESCRIPTION
**Pull request by borracciaBlu**

### CODE REVIEW

**Comment by borracciaBlu** [comment]
Hi,

I've been facing a case in which the file to prepend had the utf-8 BOM and after the prepend the file was broken.

So, i've added a couple of functions to detect the BOM and keep it at the beginning of the file.

**Comment by hemanth** [comment]
Sorry @borracciaBlu this went unnoticed for long! Are you still facing this issue?

**Comment by borracciaBlu** [comment]
Hi @hemanth yes i do.

To reproduce the issue generate this:

`node-sass --output-style compressed src/styles.scss dist/styles.css`

this will generate a a file starting with a  bom character.
If you try to prepend something to that file the bom characters is not more at the beginning of the file and thus the file breaks as the [meaning of that character  change](https://en.wikipedia.org/wiki/Byte_order_mark#Usage) (in this case the browser is not interpreting it properly).

**Comment by hemanth** [comment]
Sure, we are rehauling the API to be promise based, would you like to rebase? 

The lastest changes that has gone in is promised based.

Wondering if we should also port this to the patch version of  `v1` as well.

**Comment by hemanth** [comment]
@Richienb we should also port this.

**Comment by borracciaBlu** [comment]
Sorry @hemanth , @Richienb i didn't realise that the code did change so much.
I'll try the current `master` against the BOM test case and then I'll keep you update.

**Comment by borracciaBlu** [comment]
Hi @hemanth , @Richienb
Ok confirmed the BOM issue was still there even against `master`.
I did the rebase and update the tests and code according to the current code.

Let me know.

**Comment by hemanth** [comment]
Classic, thank you.

**Pull request merged**
